name: law_india
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  animations: ^2.0.11
  fuzzywuzzy: ^1.1.1
  provider: ^6.0.1
  scrollable_positioned_list: ^0.3.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/data/chapter_1.json
    - assets/data/chapter_2.json
    - assets/data/chapter_3.json
    - assets/data/chapter_4.json
    - assets/data/chapter_5.json
    - assets/data/chapter_6.json
    - assets/data/chapter_7.json
    - assets/data/chapter_8.json
    - assets/data/chapter_9.json
    - assets/data/chapter_10.json
    - assets/data/chapter_11.json
    - assets/data/chapter_12.json
    - assets/data/chapter_13.json
    - assets/data/chapter_14.json
    - assets/data/chapter_15.json
    - assets/data/chapter_16.json
    - assets/data/chapter_17.json
    - assets/data/chapter_18.json
    - assets/data/chapter_19.json
    - assets/data/chapter_20.json
